#!/bin/bash
sessions=$(command kak -l | grep -v dead)
blank=""
input=""
for session in $sessions; do
    export session
    pwd=$(krc get %sh[pwd])
    eval "set -- $(krc get %val[client_list])"
    for client; do
        export client
        printf -v blank '%s\n%s' "$blank" "session=$session client=$client krc send info"
        printf -v input '%s\n%s\t%s\t%s\t%s' "$input" "$session" "$client" "$(krc get %val[bufname])" "$pwd"
    done
done
printf %s "$input" | column -s $'\t' -t |
     fzf --preview "$blank; session={1} client={2} krc send info -markup "'"$(figlet {1} {2} -f big)"' --preview-window down,0 |
     awk '{print "export session=" $1 "; export client=" $2}'

