#!/bin/bash
sessions=$(command kak -l | grep -v dead)
{
    for session in $sessions; do
        export session
        pwd=$(krc get %sh[pwd])
        eval "set -- $(krc get %val[client_list])"
        for client; do
            export client
            echo -ne "$session" "\t"
            echo -ne "$client" "\t"
            echo -ne "$(krc get %val[bufname])" "\t"
            echo -ne "$pwd" "\t"
            echo
        done
    done
} | column -s $'\t' -t |
    fzf |
    awk '{print "export session=" $1 "; export client=" $2}'

